#!/usr/bin/env node
'use strict';

const {
  logInfo,
  logError,
  logSystem,
  logWarn,
  stripQuotes,
  tokenizer,
  helpText
} = require('./helpers')

const {
  handleAdd,
  handlePlay,
  handleShow,
  handleQuit
} = require('./handlers')


process.stdin.setEncoding('utf8')
process.stdin.on('data', parseLine)

function parseLine(line) {
  const { command, qualifier, details } = tokenizer(line)

  if (!command) {
    logError(`please use one of the following commands:`)
    logInfo(helpText)
    return
  }

  switch (command) {
    case 'exit':
    case 'quit':
      handleQuit()
      break
    case 'show':
      handleShow(command, qualifier, details)
      break
    case 'add':
      handleAdd(details)
      break
    case 'play':
      handlePlay(details)
      break
    default:
      logError(line)
  }
}

function start() {
  logSystem('Welcome to your music collection!')
  process.stdin.resume()
}

/** ----- START ----- */
start()

module.exports = {
  parseLine,
  start,
}
